//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTester.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public Pet()
        {
            this.Vetclinics = new HashSet<Vetclinic>();
        }
    
        public int PetID { get; set; }
        public Nullable<int> PetOwnerID { get; set; }
        public string PetName { get; set; }
        public string PetType { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Size { get; set; }
        public string MedicalConcerns { get; set; }
    
        public virtual Petowner Petowner { get; set; }
        public virtual ICollection<Vetclinic> Vetclinics { get; set; }
    }
}
