//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTester.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Petowner
    {
        public Petowner()
        {
            this.Pets = new HashSet<Pet>();
        }
    
        public int PetOwnerID { get; set; }
        public string PetOwnerLastName { get; set; }
        public string PetOwnerFirstName { get; set; }
        public string PetOwnerAddress { get; set; }
        public string PetOwnerCity { get; set; }
        public string PetOwnerProvince { get; set; }
        public string PetOwnerCountry { get; set; }
        public string PetOwnerEmail { get; set; }
        public string PetOwnerPhone { get; set; }
    
        public virtual ICollection<Pet> Pets { get; set; }
    }
}
