//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTester.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vetclinic
    {
        public Vetclinic()
        {
            this.Vets = new HashSet<Vet>();
            this.Pets = new HashSet<Pet>();
            this.Vets1 = new HashSet<Vet>();
        }
    
        public int VetClinicID { get; set; }
        public string VetClinicName { get; set; }
        public string VetClinicAddress { get; set; }
        public string VetClinicCity { get; set; }
        public string VetClinicProvince { get; set; }
        public string VetClinicCountry { get; set; }
        public string VetClinicEmail { get; set; }
        public string VetClinicPhone { get; set; }
        public string OperatingHours { get; set; }
        public Nullable<int> VetID { get; set; }
    
        public virtual ICollection<Vet> Vets { get; set; }
        public virtual Vet Vet { get; set; }
        public virtual ICollection<Pet> Pets { get; set; }
        public virtual ICollection<Vet> Vets1 { get; set; }
    }
}
